version: '3'
services:
  wireguard:
    container_name: 'secure-docker'
    build: .
    restart: 'unless-stopped'
    sysctls:
      - "net.ipv4.conf.all.rp_filter=2"
      - "net.ipv6.conf.all.disable_ipv6=0"
    cap_add:
      - net_admin 
      - sys_module
    ports:
      - '8080:8080'
  test:
    container_name: 'secure-test'
    build: ./secure-test
    image: 'secure-test'
#    command: tail -f /dev/null
    command: python -m SimpleHTTPServer 8080 /
    restart: 'unless-stopped'
    network_mode: "service:wireguard"
